# Generated by Django 5.0.7 on 2024-11-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nejlepsiProjekt', '0003_category_contact_content_partner_payment_portfolium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partner_images/'),
        ),
    ]
