# Generated by Django 5.0.7 on 2024-11-17 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nejlepsiProjekt', '0004_partner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='coints',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
