# Generated by Django 5.0.7 on 2024-11-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nejlepsiProjekt', '0007_feature_partner_content_gallery_openinghours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='content',
            name='portfolium',
        ),
        migrations.AddField(
            model_name='content',
            name='partner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='nejlepsiProjekt.partner'),
            preserve_default=False,
        ),
    ]
