# Generated by Django 5.0.7 on 2024-11-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nejlepsiProjekt', '0009_feature_partner_alter_feature_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='partner',
        ),
    ]
