# Generated by Django 5.0.7 on 2024-11-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nejlepsiProjekt', '0011_alter_feature_icon_alter_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
