# Generated by Django 5.0.7 on 2024-11-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nejlepsiProjekt', '0013_city_region_alter_partner_city_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
