# Generated by Django 5.0.7 on 2024-11-26 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nejlepsiProjekt', '0014_alter_partner_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='nejlepsiProjekt.city'),
        ),
    ]
